dir <- "/Volumes/data/code/datasciencecoursera/RProgramming/prog1/specdata"
source("/Volumes/data/code/datasciencecoursera/RProgramming/prog1/pollutantmean.R")
pollutantmean(dir, "sulfate", 1:10)
pollutantmean(dir, "nitrate", 70:72)
pollutantmean(dir, "nitrate", 23)
source("/Volumes/data/code/datasciencecoursera/RProgramming/prog1/complete.R")
complete(dir, 1)
complete(dir, c(2, 4, 8, 10, 12))
complete(dir, 30:25)
source("/Volumes/data/code/datasciencecoursera/RProgramming/prog1/corr.R")
source("/Volumes/data/code/datasciencecoursera/RProgramming/prog1/complete.R")
cr <- corr(dir, 150)
head(cr)
summary(cr)
cr <- corr(dir, 400)
head(cr)
summary(cr)
cr <- corr(dir, 5000)
summary(cr)
length(cr)
cr <- corr(dir)
summary(cr)
length(cr)
source("/Volumes/data/code/datasciencecoursera/RProgramming/prog1/rprog-scripts-submitscript1.R")
